version: "3"

services:
  vs2test:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.18.2"
      TYPE: "FORGE"
      FORGE_VERSION: "40.2.0"
      PACKWIZ_URL: "https://raw.githubusercontent.com/Everett1999/modpacktest/main/pack/pack.toml"
      MOTD: "TESTING TESTING"
      DIFFICULTY: "HARD"
      ENABLE_COMMAND_BLOCK: "TRUE"
      SNOOPER_ENABLED: "FALSE"
      SPAWN_PROTECTION: "0"
      MEMORY: "4G"


    tty: true
    stdin_open: true
    restart: unless-stopped